//Countries
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_COUNTRY_BY_ID = "GET_COUNTRY_BY_ID";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";
export const SORT_COUNTRIES_BY_NAME_ASC_DESC = "SORT_COUNTRIES_BY_NAME_ASC_DESC";
export const SORT_BY_POPULATION_ASC_DESC = "SORT_BY_POPULATION_ASC_DESC";
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
export const SORT_CONTINENT_BY_NAME = "SORT_CONTINENT_BY_NAME";

//Probando paginacion desde redux
export const SET_COUNTRY_ORDER = "SET_COUNTRY_ORDER";
export const SET_COUNTRY_POPULATION = "SET_COUNTRY_POPULATION";
export const SET_COUNTRY_CONTINENT = "SET_COUNTRY_CONTINENT";
export const PAGINATION_NEXT = "PAGINATION_NEXT";
export const PAGINATION_PREV = "PAGINATION_PREV";

// export const PAGINATION = "PAGINATION";
export const CLEAN = "CLEAN";